### ISSUE TITLE
Xp Orbs

### ISSUE THREAD

**Issue by ThunderLord95** [AcomputerdogMC/KeepXP#1]
The players keep their experience on death, however they still drop the orbs making it a free increase to their amount of experience.

**Comment by ThunderLord95** [comment]
This might be an issue with the jar the server is running on, however I'm not certain.

**Comment by ThunderLord95** [comment]
Seem to have figured it out nevermind

**Comment by warriordog** [comment]
@ThunderLord95 I'm glad you figured it out, but you should know that this plugin is abandoned. I'm no longer maintaining or even using it. The same is true of all the plugins on this account.
